<?php

/**
 * @file
 *
 */
include_once('includes/alma.reservation.inc');
define('ALMA_AUTH_BLOCKED', '4e5531951f55ab8f6895684999c69c2');

function  alma_pickup_branches() {
  /* static $branches;
  if( !isset($branches) ){
    $branches = alma_client_invoke('get_reservation_branches');
  }

  return $branches;*/
  return alma_reservation_pickup_branches();
}

/**
 * Implements hook_requirements().
 */
function alma_requirements($phase) {
  $requirements = array();
  // Ensure translations don't break at install time.
  $t = get_t();

  if (!function_exists('simplexml_load_string')) {
    $requirements['simplexml'] = array(
      'title' => 'SimpleXML',
      'description' => $t('The Alma module requires SimpleXML to function. Please install and/or enable SimpleXML in your PHP configuration.'),
      'severity' => REQUIREMENT_ERROR,
    );
  }

  return $requirements;
}

/**
 * Implements hook_ding_provider().
 */
function alma_ding_provider() {
  $path = drupal_get_path('module', 'alma');

  return array(
    'title' => 'Alma provider',
    'settings' => 'alma_settings_form',
    'provides' => array(
      'availability' => array(
        'prefix' => 'availability',
        'file' => $path . '/includes/alma.availability.inc',
      ),
      'debt' => array(
        'prefix' => 'debt',
        'file' => $path . '/includes/alma.debt.inc',
      ),
      'loan' => array(
        'prefix' => 'loan',
        'file' => $path . '/includes/alma.loan.inc',
      ),
      'reservation' => array(
        'prefix' => 'reservation',
        'file' => $path . '/includes/alma.reservation.inc',
      ),
      'user' => array(
        'prefix' => 'user',
        'file' => $path . '/includes/alma.user.inc',
      ),
    ),
  );
}

/**
 * Form callback for provider module settings.
 *
 * This is a regular form callback.
 */
function alma_settings_form() {
  $form['alma'] = array(
    '#type' => 'fieldset',
    '#title' => t('Alma service settings'),
    '#tree' => FALSE,
  );

  $form['alma']['alma_base_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Alma base URL'),
    '#description' => t('Base URL for Alma service.'),
    '#required' => TRUE,
    '#default_value' => variable_get('alma_base_url', ''),
  );

  $form['alma']['alma_enable_logging'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable logging'),
    '#default_value' => variable_get('alma_enable_logging', FALSE),
    '#description' => t('Logs requests to the Alma webservice. Sensitive information such as CPR number and PIN code is stripped from the requests.'),
  );

  return system_settings_form($form);
}


/**
 * Return a fully instantiated AlmaClient instance.
 */
function alma_client() {
  // This is basically a singleton. We also wait until right before
  // instantiating to include our required classes. That seems like a
  // decent performance tradeoff instead of loading everything on every
  // page load.
  static $client;
  if (!isset($client)) {
    $path = drupal_get_path('module', 'alma');
    try {
      $client = new AlmaClient(variable_get('alma_base_url', ''));
    }
    catch (Exception $e) {
      watchdog('alma', 'Constructor error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
      return NULL;
    }

  }
  return $client;
}

/**
 * Calls the Alma backend, possibly caching the result.
 *
 * @param $method
 *   The desired method.
 * @param ...
 *   Arguments to the method.
 *
 * @return mixed
 *   NULL on error, or the result of the method call.
 */
function alma_client_invoke($method) {
  $args = func_get_args();
  array_shift($args); // Lose the method.
  $client = alma_client(); 
  
  // @todo do not use try/catch. call_user_func_array returns false on failure
  try {
    $result = call_user_func_array(array($client, $method), $args);
  }
  catch (Exception $e) {
    watchdog('alma', '@method error: “@message”', array('@method' => $method, '@message' => $e->getMessage()), WATCHDOG_ERROR);
    throw $e;
  }

  return $result;
}

/**
 * Get the complete organisation info from Alma.
 *
 * Includes branches, departments, locations, sublocations and collections. The
 * information is cache until the cache is cleared or the reset parameter is
 * TRUE.
 *
 * @param boolean $reset
 * Optional. If TRUE reset the cached data and reload.
 * @return array
 * Array of the different organisational unit, each an array of their
 * member units.
 */
function alma_get_organisation($reset = FALSE) {
  // Return data from cache if available.
  static $organisation;
  if (!$organisation || $reset) {
    if (($cache = cache_get('alma_organisation')) && !empty($cache->data) && !$reset) {
      $organisation = $cache->data;
    }
    else {
      $organisation = array(
        'branch' => alma_client_invoke('get_branches'),
        'department' => alma_client_invoke('get_departments'),
        'location' => alma_client_invoke('get_locations'),
        'sublocation' => alma_client_invoke('get_sublocations'),
        'collection' => alma_client_invoke('get_collections'),
        'reservation' => alma_client_invoke('get_reservation_branches'),
      );

      // Cache output for 24 hours if we got all the data correctly.
      if ($organisation['branch'] && $organisation['department'] &&
          $organisation['location'] && $organisation['sublocation'] &&
          $organisation['collection'] && $organisation['reservation']) {
        cache_set('alma_organisation', $organisation, 'cache');
      }
    }
  }

  return $organisation;
}

/**
 * Get patron data from Alma.
 *
 * @param array $creds
 *   Array with 'name' and 'pass' keys, used to authenticate user with Alma.
 * @param boolean $reset
 *   Reset static caching for this function.
 * @return stdClass
 *   Patron object.
 */
function alma_get_patron($creds = NULL, $reset = TRUE) {
  if (is_null($creds)) {
    // Get creds, which may throw an exception that login is required.
    global $user;
    $creds = ding_user_get_creds($user);
  }

  static $patron;
  if (!$patron || $reset) {
    $info = alma_client_invoke('get_patron_info', $creds['name'], $creds['pass'], TRUE);
    $organisation = alma_get_organisation();
    $patron = array(
      'name' => $info['user_name'],
      'email' => isset($info['mails'][0]) ? $info['mails'][0]['mail'] : '',
      'address' => isset($info['addresses'][0]) ? $info['addresses'][0]['street'] : '',
      'postal' => isset($info['addresses'][0]) ? $info['addresses'][0]['postal_code'] : '',
      'city' => isset($info['addresses'][0]) ? $info['addresses'][0]['city'] : '',
      'mobile' => isset($info['phones'][0]) ? $info['phones'][0]['phone'] : '',
      'branch' => $info['preferences']['patron_branch'],
      'branchName' => $organisation['branch'][$info['preferences']['patron_branch']],
    );
  }

  return (object) $patron;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * pjo notes: profile2
 * Add in pincode validation.
 */
function alma_form_user_profile_form_alter(&$form, &$form_state) {
  // Ensure that we're dealing with a provider user.
  if (!ding_user_is_provider_user($form_state['user'])) {
    return;
  }

  

  // only show pincode fields once (on the general account)
  /* if( $form['#user_category'] != 'account' ){
    unset($form['account']['pincode']);
    }*/
 
   /*  dpm($form_id);
  dpm($form);
  dpm($form_state);*/

  global $user;
  $profile2 = profile2_load_by_user($user, 'provider_alma');

  dpm('ALMA PROFILE FORM ALTER');
  dpm($form_state);
  dpm($form);
  dpm('ALMA PROFILE2');
  dpm($profile2);
  
  // pjo attach profile2 form to get profile2 specific form eidt-fields.
  // fields could be shown by editing permission->profile2, but profile2 adds a tab and we don't want that.
  if(ding_user_is_provider_user($user) && $profile2) { 
    $form_state['profiles'] = array('provider_alma'=>$profile2);
    profile2_attach_form($form, $form_state);
  }
  // custom validator 
  //  $form['#validate'][] = 'alma_profile_form_validate';

  // testing - we might need another submit routine
  $form['#submit'][] = 'alma_test_submit';
}

/*function alma_profile_form_validate(&$form, &$form_state) {
    if (!empty($form_state['values']['pincode'])) {
    if (!preg_match('/^\d{4}$/', $form_state['values']['pincode'])) {
      form_error($form['account']['pincode'], t('Pincode must be four numbers.'));
    }
  }
  }*/

function alma_test_submit(&$form, &$form_state) {
  dpm('TESTSUBMIT');
  dpm($form);
}


/**
 * Implements hook_profile2_presave().
 *
 * Sends changes to Alma and updates profile with real values.
 */
function alma_profile2_presave($profile) {
  if ($profile->type == 'provider_alma' &&
      !isset($profile->alma_init) &&
      !empty($profile->original->alma_preferred_branch) &&
      $profile->alma_preferred_branch != $profile->original->alma_preferred_branch) {
    $langs = field_language('profile2', $profile);
    $changes['preferred_branch'] = $profile->alma_preferred_branch[$langs['alma_preferred_branch']][0]['value'];

    $creds = ding_user_get_creds($profile);
    $res = alma_client_invoke('update_userinfo', $creds['name'], $creds['pass'], $changes);
    if ($res !== TRUE) {
      // Call failed, throw exception.
      if (is_string($res)) {
        $exception_message = t('Update userinfo failed, message: @message', array('@message' => $res));
      }
      else {
        $exception_message = t('Update userinfo failed.');
      }
      throw new Exception($exception_message);
    }

    // Update the profile with whatever Alma says.
    $creds = ding_user_get_creds($profile);
    if (($userStatus = _alma_user_status($creds, TRUE)) && isset($userStatus->userInfo)) {
      alma_profile_update($profile, $userStatus->userInfo);
    };
  }
}

/**
 * Implements hook_profile2_view(),
 */
function alma_profile2_view($profile, $view_mode, $langcode) {
  
  dpm('TESTHEST');

  $creds = ding_user_get_creds($profile);
  if (($userStatus = _alma_user_status($creds, TRUE)) && isset($userStatus->userInfo)) {
    $userinfo = $userStatus->userInfo;
    $props = array(
      'userFirstName',
      'userLastName',
      'userEmail',
      'userAddress',
      'userPostCode',
      'userCity',
      'userVillage',
      'userTelephone',
      'userMobilePhone',
    );
    foreach ($props as $prop) {
      $data[$prop] = isset($userinfo->$prop) ? $userinfo->$prop : '';
    }

    $profile->content['name'] = array(
      '#type' => 'item',
      '#title' => t('Name'),
      '#markup' => join(' ', array_filter(array($data['userFirstName'], $data['userLastName']))),
    );

    $address_parts = array($data['userAddress']);
    if (!empty($data['userVillage']) && $data['userVillage'] != $data['userCity']) {
      $address_parts[] = $data['userVillage'];
    }
    if (!empty($data['userPostCode']) || !empty($data['userCity'])) {
      $address_parts[] = join(' ', array_filter(array($data['userPostCode'], $data['userCity'])));
    }

    // @todo: really, there should be a template for this.
    $profile->content['address'] = array(
      '#type' => 'item',
      '#title' => t('Address'),
      '#markup' => '<p>' . join('</p><p>', $address_parts) . '</p>',
    );
  };
}


